/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Conexao;
import Controle.ModeloTabela;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Matheus Moura
 */
public class frmAtendimentoAgendado extends javax.swing.JFrame {

    Conexao con = new Conexao();
    String selecao;

    /**
     * Creates new form frmAtendimentoAgendado
     */
    public frmAtendimentoAgendado() {
        initComponents();
        con.conectar();
        try {
            preencherTabelaAtendimentos("select * from fastflowcreas.familia_atendimento, fastflowcreas.usuario where fastflowcreas.familia_atendimento.id_usuario = fastflowcreas.usuario.id_usuario order by data_atendimento");
        } catch (SQLException ex) {
            Logger.getLogger(frmAtendimentoAgendado.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButtonData = new javax.swing.JRadioButton();
        jDateChooserDataInicio = new com.toedter.calendar.JDateChooser();
        jDateChooserDataFim = new com.toedter.calendar.JDateChooser();
        jRadioButtonRealizado = new javax.swing.JRadioButton();
        jRadioButtonPendente = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAtendimentos = new javax.swing.JTable();
        jRadioButtonTodos = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jRadioButtonCancelados = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        buttonGroup1.add(jRadioButtonNome);
        jRadioButtonNome.setSelected(true);
        jRadioButtonNome.setText("NOME");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        buttonGroup1.add(jRadioButtonData);
        jRadioButtonData.setText("DATA");

        buttonGroup1.add(jRadioButtonRealizado);
        jRadioButtonRealizado.setText("REALIZADOS");

        buttonGroup1.add(jRadioButtonPendente);
        jRadioButtonPendente.setText("PENDENTES");

        jTableAtendimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableAtendimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAtendimentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAtendimentos);

        buttonGroup1.add(jRadioButtonTodos);
        jRadioButtonTodos.setText("TODOS");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search-file256_25202.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCancelados);
        jRadioButtonCancelados.setText("CANCELADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonData)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDateChooserDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooserDataFim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonPendente)
                                    .addComponent(jRadioButtonRealizado))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonCancelados)
                                    .addComponent(jRadioButtonTodos)))
                            .addComponent(jButton1))
                        .addGap(0, 468, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonNome)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonRealizado)
                    .addComponent(jRadioButtonCancelados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonData)
                    .addComponent(jDateChooserDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonPendente)
                        .addComponent(jRadioButtonTodos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1002, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        if (jRadioButtonNome.isSelected()) {
            try {
                preencherTabelaAtendimentos("select * from fastflowcreas.familia_atendimento, fastflowcreas.usuario where fastflowcreas.familia_atendimento.id_usuario = fastflowcreas.usuario.id_usuario and fastflowcreas.usuario.nome_usuario like '%" + jTextField1.getText().toUpperCase() + "%' order by data_atendimento");
            } catch (SQLException ex) {
                Logger.getLogger(frmAtendimentoAgendado.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }

    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jRadioButtonData.isSelected()) {
            try {
                if (jDateChooserDataInicio.getDate() != null || jDateChooserDataFim.getDate() != null) {
                    java.util.Date pegaRecebDataInicio = jDateChooserDataInicio.getDate();
                    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                    String dataInicio = formato.format(pegaRecebDataInicio);

                    java.util.Date pegaRecebDataFim = jDateChooserDataFim.getDate();
                    SimpleDateFormat formato1 = new SimpleDateFormat("yyyy-MM-dd");
                    String dataFim = formato1.format(pegaRecebDataFim);
                    preencherTabelaAtendimentos("select * from fastflowcreas.familia_atendimento, fastflowcreas.usuario where fastflowcreas.familia_atendimento.id_usuario = fastflowcreas.usuario.id_usuario and data_atendimento >= '" + dataInicio + "' and  data_atendimento < '" + dataFim + "' order by data_atendimento");
                } else {
                    JOptionPane.showMessageDialog(null, "INFORME O INTERVALO DE DATAS");
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmAtendimentoAgendado.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }
        if (jRadioButtonTodos.isSelected()) {
            try {
                preencherTabelaAtendimentos("select * from fastflowcreas.familia_atendimento, fastflowcreas.usuario where fastflowcreas.familia_atendimento.id_usuario = fastflowcreas.usuario.id_usuario");
            } catch (SQLException ex) {
                Logger.getLogger(frmAtendimentoAgendado.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }
        if (jRadioButtonPendente.isSelected()) {
            try {
                preencherTabelaAtendimentos("select * from fastflowcreas.familia_atendimento, fastflowcreas.usuario where fastflowcreas.familia_atendimento.id_usuario = fastflowcreas.usuario.id_usuario and situacao_atendimento = 'PENDENTE' order by data_atendimento");
            } catch (SQLException ex) {
                Logger.getLogger(frmAtendimentoAgendado.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }
        if (jRadioButtonRealizado.isSelected()) {
            try {
                preencherTabelaAtendimentos("select * from fastflowcreas.familia_atendimento, fastflowcreas.usuario where fastflowcreas.familia_atendimento.id_usuario = fastflowcreas.usuario.id_usuario and situacao_atendimento = 'REALIZADO' order by data_atendimento");
            } catch (SQLException ex) {
                Logger.getLogger(frmAtendimentoAgendado.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }
        if (jRadioButtonCancelados.isSelected()) {
            try {
                preencherTabelaAtendimentos("select * from fastflowcreas.familia_atendimento, fastflowcreas.usuario where fastflowcreas.familia_atendimento.id_usuario = fastflowcreas.usuario.id_usuario and situacao_atendimento = 'CANCELADO' order by data_atendimento");
            } catch (SQLException ex) {
                Logger.getLogger(frmAtendimentoAgendado.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableAtendimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAtendimentosMouseClicked
        String cod = "" + jTableAtendimentos.getValueAt(jTableAtendimentos.getSelectedRow(), 0);
        String data = "" + jTableAtendimentos.getValueAt(jTableAtendimentos.getSelectedRow(), 1);
        String usuario = "" + jTableAtendimentos.getValueAt(jTableAtendimentos.getSelectedRow(), 2);
        String tipo = "" + jTableAtendimentos.getValueAt(jTableAtendimentos.getSelectedRow(), 3);
        String descricao = "" + jTableAtendimentos.getValueAt(jTableAtendimentos.getSelectedRow(), 4);
        String situacao = "" + jTableAtendimentos.getValueAt(jTableAtendimentos.getSelectedRow(), 5);
        frmDescricaoAtendimento frmDesc = new frmDescricaoAtendimento(cod, data, usuario, tipo, descricao, situacao);
        frmDesc.setVisible(true);
    }//GEN-LAST:event_jTableAtendimentosMouseClicked
    public void preencherTabelaAtendimentos(String sql) throws SQLException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD", "DATA", "USUARIO", "TIPO ATENDIMENTO", "DESCRICAO", " SITUACAO"};
        con.excutaSQL(sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("id_familia_atendimento"),
                    con.rs.getString("data_atendimento"),
                    con.rs.getString("nome_usuario"),
                    con.rs.getString("tipo_atendimento"),
                    con.rs.getString("descricao_atendimento"),
                    con.rs.getString("situacao_atendimento")});

            } while (con.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "SEM REGISTROS");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableAtendimentos.setModel(modelo);
        jTableAtendimentos.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableAtendimentos.getColumnModel().getColumn(0).setResizable(true);
        jTableAtendimentos.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableAtendimentos.getColumnModel().getColumn(1).setResizable(true);
        jTableAtendimentos.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTableAtendimentos.getColumnModel().getColumn(2).setResizable(true);
        jTableAtendimentos.getColumnModel().getColumn(3).setPreferredWidth(250);
        jTableAtendimentos.getColumnModel().getColumn(3).setResizable(true);
        jTableAtendimentos.getColumnModel().getColumn(4).setPreferredWidth(300);
        jTableAtendimentos.getColumnModel().getColumn(4).setResizable(true);
        jTableAtendimentos.getColumnModel().getColumn(5).setPreferredWidth(150);
        jTableAtendimentos.getColumnModel().getColumn(5).setResizable(true);
        jTableAtendimentos.setAutoResizeMode(jTableAtendimentos.AUTO_RESIZE_ALL_COLUMNS);
        jTableAtendimentos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAtendimentoAgendado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAtendimentoAgendado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAtendimentoAgendado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAtendimentoAgendado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAtendimentoAgendado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooserDataFim;
    private com.toedter.calendar.JDateChooser jDateChooserDataInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCancelados;
    private javax.swing.JRadioButton jRadioButtonData;
    private javax.swing.JRadioButton jRadioButtonNome;
    private javax.swing.JRadioButton jRadioButtonPendente;
    private javax.swing.JRadioButton jRadioButtonRealizado;
    private javax.swing.JRadioButton jRadioButtonTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAtendimentos;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
