/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Conexao;
import Controle.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Matheus Moura
 */
public class frmConsultaFamilia extends javax.swing.JFrame {

    Conexao con = new Conexao();

    /**
     * Creates new form frmConsultaFamilia
     */
    public frmConsultaFamilia() {
        initComponents();
        con.conectar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel29 = new javax.swing.JLabel();
        jTextFieldPesquisaFamilia = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableConsultaFamilia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTA DE FAMILIAS");
        setResizable(false);

        jLabel29.setText("PESQUISA DE FAMILIA ( USUARIO )");
        jLabel29.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldPesquisaFamilia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaFamiliaKeyReleased(evt);
            }
        });

        jTableConsultaFamilia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableConsultaFamilia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaFamiliaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableConsultaFamilia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPesquisaFamilia)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPesquisaFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(897, 606));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisaFamiliaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaFamiliaKeyReleased
        con.conectar();
        try {
            preencherTabelaConsultaFamilia("select * from fastflowcreas.familia_usuario, fastflowcreas.usuario where fastflowcreas.familia_usuario.id_usuario = fastflowcreas.usuario.id_usuario and fastflowcreas.usuario.nome_usuario like '%" + jTextFieldPesquisaFamilia.getText().toUpperCase() + "%' order by fastflowcreas.familia_usuario.id_familia");
        } catch (SQLException ex) {
            Logger.getLogger(jfrmCadastroFamilia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldPesquisaFamiliaKeyReleased

    private void jTableConsultaFamiliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaFamiliaMouseClicked
        int id_familia = Integer.parseInt("" + jTableConsultaFamilia.getValueAt(jTableConsultaFamilia.getSelectedRow(), 0));
        frmProntuarioFamiliaCompleto frmProntuario = new frmProntuarioFamiliaCompleto(id_familia);
        frmProntuario.setVisible(true);
    }//GEN-LAST:event_jTableConsultaFamiliaMouseClicked
    public void preencherTabelaConsultaFamilia(String sql) throws SQLException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"FAMILIA", "USUARIO", "PARENTESCO", "CPF", "RG", "NIS"};
        con.excutaSQL(sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("id_familia"), con.rs.getString("nome_usuario"), con.rs.getString("parentesco"), con.rs.getString("cpf"), con.rs.getString("rg"), con.rs.getString("nis")});
            } while (con.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "USUARIO NAO ENCONTRADO");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableConsultaFamilia.setModel(modelo);
        jTableConsultaFamilia.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableConsultaFamilia.getColumnModel().getColumn(0).setResizable(true);
        jTableConsultaFamilia.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTableConsultaFamilia.getColumnModel().getColumn(1).setResizable(true);
        jTableConsultaFamilia.getColumnModel().getColumn(2).setPreferredWidth(230);
        jTableConsultaFamilia.getColumnModel().getColumn(2).setResizable(true);
        jTableConsultaFamilia.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableConsultaFamilia.getColumnModel().getColumn(3).setResizable(true);
        jTableConsultaFamilia.getColumnModel().getColumn(4).setPreferredWidth(135);
        jTableConsultaFamilia.getColumnModel().getColumn(4).setResizable(true);
        jTableConsultaFamilia.getColumnModel().getColumn(5).setPreferredWidth(135);
        jTableConsultaFamilia.getColumnModel().getColumn(5).setResizable(true);
        jTableConsultaFamilia.getTableHeader().setReorderingAllowed(false);
        jTableConsultaFamilia.setAutoResizeMode(jTableConsultaFamilia.AUTO_RESIZE_ALL_COLUMNS);
        jTableConsultaFamilia.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConsultaFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConsultaFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConsultaFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConsultaFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConsultaFamilia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel29;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableConsultaFamilia;
    private javax.swing.JTextField jTextFieldPesquisaFamilia;
    // End of variables declaration//GEN-END:variables
}
