/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Conexao;
import Controle.ControleUsuario;
import Controle.ModeloTabela;
import Modelo.ModeloUsuario;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Matheus Moura
 */
public class jfrmRegistroUsuario extends javax.swing.JFrame {

    Conexao con = new Conexao();
    int id_usuario, id_usuario_relato;
    Timestamp dataDeHoje = new Timestamp(System.currentTimeMillis());

    /**
     * Creates new form jfrmManterUsuario
     */
    public jfrmRegistroUsuario() {
        initComponents();
        con.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTabbedPanePesquisa = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldConsultaUsuario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePesquisaUsuario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jRadioButtonFeminino = new javax.swing.JRadioButton();
        jDateChooserDataNascimento = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabelCod = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonSabeSim = new javax.swing.JRadioButton();
        jRadioButtonSabeNao = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonFrequentaSim = new javax.swing.JRadioButton();
        jRadioButtonFrequentaNao = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxEscolaridade = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButtonPossuiSim = new javax.swing.JRadioButton();
        jRadioButtonPossuiNao = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxCondicao = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldQualificao = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldRendaMensal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxDeficiencia = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCuidador = new javax.swing.JTextField();
        jButtonInserirSaude = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDeficiencia = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxRelato = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jButtonInserirRelato = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jRadioButtonSituacaoSim = new javax.swing.JRadioButton();
        jRadioButtonSituacaoNao = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableRelatos = new javax.swing.JTable();
        jButtonAtualizarRelato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRO DE USUARIOS");
        setResizable(false);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/upgradedb_database_arrow_6329.png"))); // NOI18N
        jButtonSalvar.setText("ATUALIZAR");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel_stop_exit_1583 (1).png"))); // NOI18N
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel17.setText("NOME DO USUARIO");

        jTextFieldConsultaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldConsultaUsuarioKeyReleased(evt);
            }
        });

        jTablePesquisaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePesquisaUsuario);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldConsultaUsuario)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldConsultaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPanePesquisa.addTab("PESQUISA", jPanel14);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setText("CODIGO USUARIO:");

        jLabel1.setText("NOME COMPLETO");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextFieldNome.setEnabled(false);

        jLabel2.setText("CPF");
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextFieldCpf.setEnabled(false);

        jLabel3.setText("RG");
        jLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextFieldRg.setEnabled(false);

        jLabel4.setText("NIS");
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextFieldNis.setEnabled(false);

        jLabel5.setText("SEXO");
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jRadioButtonMasculino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setSelected(true);
        jRadioButtonMasculino.setText("MASCULINO");
        jRadioButtonMasculino.setContentAreaFilled(false);
        jRadioButtonMasculino.setEnabled(false);

        jRadioButtonFeminino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonFeminino);
        jRadioButtonFeminino.setText("FEMININO");
        jRadioButtonFeminino.setContentAreaFilled(false);
        jRadioButtonFeminino.setEnabled(false);

        jDateChooserDataNascimento.setEnabled(false);

        jLabel6.setText("DATA DE NASCIMENTO");
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel18.setText("BAIRRO");
        jLabel18.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextFieldBairro.setEnabled(false);

        jLabel19.setText("ENDERECO");
        jLabel19.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextFieldEndereco.setEnabled(false);

        jLabel20.setText("NUMERO");
        jLabel20.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextFieldNumero.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCpf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(jTextFieldNis)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCod, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonFeminino)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonMasculino))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooserDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldNome)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEndereco))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jTextFieldNumero))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabelCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonMasculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFeminino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(213, 213, 213))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPanePesquisa.addTab("DADOS PESSOAIS", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SABE LER E ESCREVER?");
        jLabel7.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jRadioButtonSabeSim.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButtonSabeSim);
        jRadioButtonSabeSim.setSelected(true);
        jRadioButtonSabeSim.setText("SIM");
        jRadioButtonSabeSim.setContentAreaFilled(false);
        jRadioButtonSabeSim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonSabeSim.setEnabled(false);

        jRadioButtonSabeNao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButtonSabeNao);
        jRadioButtonSabeNao.setText("NAO");
        jRadioButtonSabeNao.setContentAreaFilled(false);
        jRadioButtonSabeNao.setEnabled(false);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FREQUENTA ESCOLA ATUALMENTE?");
        jLabel8.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jRadioButtonFrequentaSim.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(jRadioButtonFrequentaSim);
        jRadioButtonFrequentaSim.setSelected(true);
        jRadioButtonFrequentaSim.setText("SIM");
        jRadioButtonFrequentaSim.setContentAreaFilled(false);
        jRadioButtonFrequentaSim.setEnabled(false);

        jRadioButtonFrequentaNao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(jRadioButtonFrequentaNao);
        jRadioButtonFrequentaNao.setText("NAO");
        jRadioButtonFrequentaNao.setContentAreaFilled(false);
        jRadioButtonFrequentaNao.setEnabled(false);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ESCOLARIDADE");
        jLabel9.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jComboBoxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "0 – NUNCA FREQUENTOU ESCOLA", "1 -  CRECHE", "2 -  EDUCAÇAO INFANTIL", "11 – 1 ANO E. FUNDAMENTAL", "12 – 2 ANO E. FUNDAMENTAL", "13 – 3 ANO E. FUNDAMENTAL", "14 – 4 ANO E. FUNDAMENTAL", "15 – 5 ANO E. FUNDAMENTAL", "16 – 6 ANO E. FUNDAMENTAL", "17 – 7 ANO E. FUNDAMENTAL", "18 – 8 ANO E. FUNDAMENTAL", "19 – 9 ANO E. FUNDAMENTAL", "21 – 1 ANO E. MEDIO", "22 – 2 ANO E. MEDIO", "23 – 3 ANO E. MEDIO", "30 – SUPERIOR INCOMPLETO", "31 – SUPERIOR COMPLETO", "40 – EJA – ENSINO FUNDAMENTAL", "41 – EJA – ENSINO MEDIO", "99 - OUTROS" }));
        jComboBoxEscolaridade.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSabeNao)
                            .addComponent(jRadioButtonSabeSim)
                            .addComponent(jRadioButtonFrequentaNao)
                            .addComponent(jRadioButtonFrequentaSim))
                        .addGap(0, 567, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxEscolaridade, 0, 614, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonSabeSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonSabeNao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFrequentaSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFrequentaNao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPanePesquisa.addTab("EDUCACAO", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("POSSUI CARTEIRA DE TRABALHO?");
        jLabel10.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jRadioButtonPossuiSim.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(jRadioButtonPossuiSim);
        jRadioButtonPossuiSim.setSelected(true);
        jRadioButtonPossuiSim.setText("SIM");
        jRadioButtonPossuiSim.setContentAreaFilled(false);
        jRadioButtonPossuiSim.setEnabled(false);

        jRadioButtonPossuiNao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(jRadioButtonPossuiNao);
        jRadioButtonPossuiNao.setText("NAO");
        jRadioButtonPossuiNao.setContentAreaFilled(false);
        jRadioButtonPossuiNao.setEnabled(false);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CONDICAO DE OCUPACAO");
        jLabel11.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jComboBoxCondicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "0 - NAO TRABALHA", "1 - TRABALHADOR POR CONTA PROPRIA (BICO, AUTONOMO)", "2 - TRABALHADOR TEMPORARIO EM AREA RURAL", "3 - EMPREGADO SEM CARTEIRA DE TRABALHO ASSINADA", "4 - EMPREGADO COM CARTEIRA DE TRABALHO ASSINADA", "5 - TRABALHADOR DOMESTICO SEM CARTEIRA DE TRABALHO ASSINADA", "6 - TRABALHADOR DOMESTICO COM CARTEIRA DE TRABALHO ASSINADA", "7 - TRABALHADOR NAO-REMUNERADO", "8 - MILITAR OU SERVIDOR PUBLICO", "9 – EMPREGADOR", "10 – ESTAGIARIO", "11 – APRENDIZ (EM CONDIÇAO LEGAL)" }));
        jComboBoxCondicao.setEnabled(false);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("QUALIFICACAO PROFISSIONAL");
        jLabel12.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextFieldQualificao.setEnabled(false);

        jLabel13.setText("RENDA MENSAL EM REAIS");
        jLabel13.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextFieldRendaMensal.setText("0");
        jTextFieldRendaMensal.setToolTipText("Ex: 80.0");
        jTextFieldRendaMensal.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonPossuiSim)
                                    .addComponent(jRadioButtonPossuiNao))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldQualificao)
                            .addComponent(jComboBoxCondicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldRendaMensal))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPossuiSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPossuiNao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQualificao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRendaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPanePesquisa.addTab("TRABALHO", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setText("DEFICIENCIA");
        jLabel14.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jComboBoxDeficiencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01 - CEGUEIRA", "02 - BAIXA VISAO", "03 - SURDEZ SEVERA/PROFUNDA", "04 - SURDEZ LEVE/MODERADA", "05 - DEFICIENCIA FISICA", "06 - DEFICIENCIA MENTAL OU INTELECTUAL", "07 - SINDROME DE DOWN", "08 - TRANSTORNO/DOENCA MENTAL" }));
        jComboBoxDeficiencia.setEnabled(false);

        jLabel15.setText("CUIDADOR");
        jLabel15.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextFieldCuidador.setEnabled(false);

        jButtonInserirSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/business_application_addthedatabase_add_insert_database_db_2313.png"))); // NOI18N
        jButtonInserirSaude.setText("INSERIR");
        jButtonInserirSaude.setEnabled(false);
        jButtonInserirSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirSaudeActionPerformed(evt);
            }
        });

        jLabel16.setText("DEFICIENCIAS DO USUARIO");
        jLabel16.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTableDeficiencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDeficiencia.setEnabled(false);
        jScrollPane1.setViewportView(jTableDeficiencia);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCuidador)
                    .addComponent(jComboBoxDeficiencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonInserirSaude, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCuidador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInserirSaude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPanePesquisa.addTab("SAUDE", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setText("RELATO");
        jLabel24.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jComboBoxRelato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01 - TRABALHO INFANTIL ", "02 - EXPLORAÇAO SEXUAL", "03 - ABUSO/VIOLENCIA SEXUAL ", "04 - VIOLENCIA FISICA", "05 - VIOLENCIA PSICOLOGICA ", "06 - NEGLIGENCIA CONTRA IDOSO ", "07 - NEGLIGENCIA CONTRA CRIANÇA ", "08 - NEGLIGENCIA CONTRA PCD ", "09 - TRAJETORIA DE RUA ", "10 - TRAFICO DE PESSOAS ", "11 - VIOLENCIA PATRIMONIAL CONTRA IDOSO OU PCD", "12 - OUTRA" }));
        jComboBoxRelato.setEnabled(false);

        jLabel25.setText("DESCRICAO");
        jLabel25.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setLineWrap(true);
        jTextAreaDescricao.setRows(5);
        jTextAreaDescricao.setEnabled(false);
        jScrollPane3.setViewportView(jTextAreaDescricao);

        jButtonInserirRelato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/business_application_addthedatabase_add_insert_database_db_2313.png"))); // NOI18N
        jButtonInserirRelato.setText("INSERIR");
        jButtonInserirRelato.setEnabled(false);
        jButtonInserirRelato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirRelatoActionPerformed(evt);
            }
        });

        jLabel22.setText("A SITUACAO PERSISTE?");
        jLabel22.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        buttonGroup5.add(jRadioButtonSituacaoSim);
        jRadioButtonSituacaoSim.setSelected(true);
        jRadioButtonSituacaoSim.setText("SIM");
        jRadioButtonSituacaoSim.setEnabled(false);

        buttonGroup5.add(jRadioButtonSituacaoNao);
        jRadioButtonSituacaoNao.setText("NAO");
        jRadioButtonSituacaoNao.setEnabled(false);

        jLabel26.setText("LISTA DE RELATOS");
        jLabel26.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTableRelatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRelatos.setEnabled(false);
        jTableRelatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRelatosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableRelatos);

        jButtonAtualizarRelato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/upgradedb_database_arrow_6329.png"))); // NOI18N
        jButtonAtualizarRelato.setText("ATUALIZAR");
        jButtonAtualizarRelato.setEnabled(false);
        jButtonAtualizarRelato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarRelatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxRelato, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jRadioButtonSituacaoSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonSituacaoNao))
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAtualizarRelato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInserirRelato, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAtualizarRelato, jButtonInserirRelato});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxRelato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonInserirRelato)
                        .addComponent(jButtonAtualizarRelato))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonSituacaoSim)
                            .addComponent(jRadioButtonSituacaoNao))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPanePesquisa.addTab("RELATOS", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePesquisa)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancelar, jButtonSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPanePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCancelar, jButtonSalvar});

        setSize(new java.awt.Dimension(655, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public boolean testarNumero(String texto) {
        try {
            Double.parseDouble(texto);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    public void limpaTexto() {
        jLabelCod.setText("");
        jTextFieldCpf.setText("");
        jTextFieldCuidador.setText("");
        jTextFieldNis.setText("");
        jTextFieldNome.setText("");
        jTextFieldQualificao.setText("");
        jTextFieldRendaMensal.setText("0");
        jTextFieldRg.setText("");
        jComboBoxCondicao.setSelectedIndex(0);
        jComboBoxEscolaridade.setSelectedIndex(0);
        jComboBoxRelato.setSelectedIndex(0);
        jComboBoxDeficiencia.setSelectedIndex(0);
        jTextAreaDescricao.setText("");
        jDateChooserDataNascimento.setDate(null);
        jTextFieldBairro.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNumero.setText("");
    }

    public void habilitaTexto() {
        jButtonSalvar.setEnabled(true);
        jButtonInserirRelato.setEnabled(true);
        jButtonInserirSaude.setEnabled(true);
        jTextFieldCpf.setEnabled(true);
        jTextFieldCuidador.setEnabled(true);
        jTextFieldNis.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldQualificao.setEnabled(true);
        jTextFieldRendaMensal.setEnabled(true);
        jTextFieldRg.setEnabled(true);
        jTableDeficiencia.setEnabled(true);
        jTableRelatos.setEnabled(true);
        jComboBoxCondicao.setEnabled(true);
        jComboBoxEscolaridade.setEnabled(true);
        jComboBoxRelato.setEnabled(true);
        jComboBoxDeficiencia.setEnabled(true);
        jRadioButtonFrequentaSim.setEnabled(true);
        jRadioButtonMasculino.setEnabled(true);
        jRadioButtonPossuiNao.setEnabled(true);
        jRadioButtonPossuiSim.setEnabled(true);
        jRadioButtonSabeNao.setEnabled(true);
        jRadioButtonSabeSim.setEnabled(true);
        jRadioButtonSituacaoNao.setEnabled(true);
        jRadioButtonSituacaoSim.setEnabled(true);
        jRadioButtonFrequentaNao.setEnabled(true);
        jRadioButtonFeminino.setEnabled(true);
        jTextAreaDescricao.setEnabled(true);
        jDateChooserDataNascimento.setEnabled(true);
        jButtonInserirRelato.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
    }

    public void desabilitaTexto() {
        jLabelCod.setEnabled(false);
        jTextFieldCpf.setEnabled(false);
        jTextFieldCuidador.setEnabled(false);
        jTextFieldNis.setEnabled(false);
        jTextFieldNome.setEnabled(false);
        jTextFieldQualificao.setEnabled(false);
        jTextFieldRendaMensal.setEnabled(false);
        jTextFieldRg.setEnabled(false);
        jTableDeficiencia.setEnabled(false);
        jTableRelatos.setEnabled(false);
        jComboBoxCondicao.setEnabled(false);
        jComboBoxEscolaridade.setEnabled(false);
        jComboBoxRelato.setEnabled(false);
        jComboBoxDeficiencia.setEnabled(false);
        jRadioButtonFrequentaSim.setEnabled(false);
        jRadioButtonMasculino.setEnabled(false);
        jRadioButtonPossuiNao.setEnabled(false);
        jRadioButtonPossuiSim.setEnabled(false);
        jRadioButtonSabeNao.setEnabled(false);
        jRadioButtonSabeSim.setEnabled(false);
        jRadioButtonSituacaoNao.setEnabled(false);
        jRadioButtonSituacaoSim.setEnabled(false);
        jRadioButtonFrequentaNao.setEnabled(false);
        jRadioButtonFeminino.setEnabled(false);
        jTextAreaDescricao.setEnabled(false);
        jDateChooserDataNascimento.setEnabled(false);
        jButtonInserirRelato.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonInserirSaude.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
    }

    public String getDataSistema() {
        Timestamp dataDeHoje = new Timestamp(System.currentTimeMillis());
        return "" + dataDeHoje + " - " + System.getProperty("login");
    }
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if (testarNumero(jTextFieldRendaMensal.getText()) == true && !jTextFieldNome.getText().trim().isEmpty() && jDateChooserDataNascimento.getDate() != null) {
            ModeloUsuario modUsuario = new ModeloUsuario();
            modUsuario.setNome_usuario(jTextFieldNome.getText().toUpperCase());
            modUsuario.setCpf(jTextFieldCpf.getText().toUpperCase());
            modUsuario.setRg(jTextFieldRg.getText().toUpperCase());
            modUsuario.setNis(jTextFieldNis.getText().toUpperCase());
            modUsuario.setBairro(jTextFieldBairro.getText().toUpperCase());
            modUsuario.setEndereco(jTextFieldEndereco.getText().toUpperCase());
            modUsuario.setNumero(jTextFieldNumero.getText().toUpperCase());
            
            if (jRadioButtonMasculino.isSelected()) {
                modUsuario.setSexo("MASCULINO");
            } else {
            }

            if (jRadioButtonFeminino.isSelected()) {
                modUsuario.setSexo("FEMININO");
            }

            if (jDateChooserDataNascimento.getDate() == null) {
                modUsuario.setData_nascimento("01/01/0001");
            } else {
                java.util.Date pega = jDateChooserDataNascimento.getDate();
                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                String data = formato.format(pega);
                modUsuario.setData_nascimento(data);
            }

            if (jRadioButtonSabeSim.isSelected()) {
                modUsuario.setSabe_ler("SIM");
            } else {
            }
            if (jRadioButtonSabeNao.isSelected()) {
                modUsuario.setSabe_ler("NAO");
            }

            if (jRadioButtonFrequentaSim.isSelected()) {
                modUsuario.setFequenta_escola("SIM");
            } else {
            }
            if (jRadioButtonFrequentaNao.isSelected()) {
                modUsuario.setFequenta_escola("NAO");
            }

            modUsuario.setEscolaridade(String.valueOf(jComboBoxEscolaridade.getSelectedItem()));

            if (jRadioButtonPossuiSim.isSelected()) {
                modUsuario.setPossui_ctps("SIM");
            } else {
            }
            if (jRadioButtonPossuiNao.isSelected()) {
                modUsuario.setPossui_ctps("NAO");
            }

            modUsuario.setCondicao_ocupacao(String.valueOf(jComboBoxCondicao.getSelectedItem()));

            modUsuario.setQualificacao_profissional(jTextFieldQualificao.getText().toUpperCase());
            modUsuario.setRenda_mensal(Double.parseDouble(jTextFieldRendaMensal.getText()));
            modUsuario.setId_usuario(id_usuario);

            modUsuario.setUltimo_registro(getDataSistema());

            ControleUsuario controlUsuario = new ControleUsuario();
            controlUsuario.AtualizarUsuario(modUsuario);

            desabilitaTexto();
            limpaTexto();

        } else {
            JOptionPane.showMessageDialog(null, "VERIFICAR OS CAMPOS!\n1 - NOME DO USUARIO NAO PODE SER NULO\n2 - A RENDA DEVE SER EM NUMERAL");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonInserirSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirSaudeActionPerformed
        ModeloUsuario modUsuario = new ModeloUsuario();
        modUsuario.setId_usuario(id_usuario);
        modUsuario.setDeficiencia(String.valueOf(jComboBoxDeficiencia.getSelectedItem()));
        modUsuario.setCuidador(jTextFieldCuidador.getText().toUpperCase());
        modUsuario.setUltimo_registro(getDataSistema());

        if (jComboBoxDeficiencia.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "INFORME A DEFICIENCIA ANTES DE INSERIR!");
        } else {
            ControleUsuario controlUsuario = new ControleUsuario();
            controlUsuario.InserirUsuarioDeficiencia(modUsuario);

            jComboBoxDeficiencia.setSelectedIndex(0);
            jTextFieldCuidador.setText("");

            try {
                preencherTabelaDeficiencia("select * from fastflowcreas.usuario_deficiencia where id_usuario =" + id_usuario);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButtonInserirSaudeActionPerformed

    private void jButtonInserirRelatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirRelatoActionPerformed
        ModeloUsuario modUsuario = new ModeloUsuario();
        modUsuario.setId_usuario(id_usuario);
        modUsuario.setRelato(String.valueOf(jComboBoxRelato.getSelectedItem()));
        modUsuario.setDescricao(jTextAreaDescricao.getText().toUpperCase());
        modUsuario.setUltimo_registro(getDataSistema());
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String data = formato.format(dataDeHoje);
        modUsuario.setData_relato(data);

        if (jRadioButtonSituacaoSim.isSelected()) {
            modUsuario.setSituacao("SIM");
        } else {
        }
        if (jRadioButtonSituacaoNao.isSelected()) {
            modUsuario.setSituacao("NAO");
        }

        if (jComboBoxRelato.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "INFORME O RELATO ANTES DE INSERIR!");
        } else {
            ControleUsuario controlUsuario = new ControleUsuario();
            controlUsuario.InserirUsuarioRelato(modUsuario);

            jComboBoxRelato.setSelectedIndex(0);
            jTextAreaDescricao.setText("");
            jRadioButtonSituacaoSim.setSelected(true);

            try {
                preencherTabelaRelato("select * from fastflowcreas.usuario_relato where id_usuario =" + id_usuario);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "SEM REGISTROS");
            }
        }
    }//GEN-LAST:event_jButtonInserirRelatoActionPerformed

    private void jTextFieldConsultaUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldConsultaUsuarioKeyReleased
        try {
            preencherTabelaConsultaUsuario("select * from fastflowcreas.usuario where nome_usuario like '%" + jTextFieldConsultaUsuario.getText().toUpperCase() + "%'");
        } catch (SQLException ex) {
            Logger.getLogger(jfrmCadastroFamilia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldConsultaUsuarioKeyReleased

    private void jTablePesquisaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaUsuarioMouseClicked
        id_usuario = Integer.parseInt("" + jTablePesquisaUsuario.getValueAt(jTablePesquisaUsuario.getSelectedRow(), 0));
        preencheUsuario("select * from fastflowcreas.usuario where fastflowcreas.usuario.id_usuario = " + id_usuario);
        try {
            preencherTabelaRelato("select * from fastflowcreas.usuario_relato where id_usuario =" + id_usuario);
            preencherTabelaDeficiencia("select * from fastflowcreas.usuario_deficiencia where id_usuario =" + id_usuario);
            habilitaTexto();
            jTabbedPanePesquisa.setSelectedIndex(1);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SEM REGISTROS");
        }
    }//GEN-LAST:event_jTablePesquisaUsuarioMouseClicked

    private void jButtonAtualizarRelatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarRelatoActionPerformed
        ModeloUsuario modUsuario = new ModeloUsuario();
        modUsuario.setId_usuario_relato(id_usuario_relato);
        modUsuario.setDescricao(jTextAreaDescricao.getText().toUpperCase());
        modUsuario.setUltimo_registro(getDataSistema());

        if (jRadioButtonSituacaoSim.isSelected()) {
            modUsuario.setSituacao("SIM");
        } else {
        }
        if (jRadioButtonSituacaoNao.isSelected()) {
            modUsuario.setSituacao("NAO");
        }

        ControleUsuario controlUsuario = new ControleUsuario();
        controlUsuario.AtualizaUsuarioRelato(modUsuario);

        jComboBoxRelato.setSelectedIndex(0);
        jTextAreaDescricao.setText("");
        jRadioButtonSituacaoSim.setSelected(true);
        jButtonAtualizarRelato.setEnabled(false);
        jButtonInserirRelato.setEnabled(true);

        try {
            preencherTabelaRelato("select * from fastflowcreas.usuario_relato where id_usuario =" + id_usuario);
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "SEM REGISTROS");
        }

    }//GEN-LAST:event_jButtonAtualizarRelatoActionPerformed

    private void jTableRelatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRelatosMouseClicked
        id_usuario_relato = Integer.parseInt("" + jTableRelatos.getValueAt(jTableRelatos.getSelectedRow(), 0));
        String descricao = "" + jTableRelatos.getValueAt(jTableRelatos.getSelectedRow(), 2);
        String situacao = "" + jTableRelatos.getValueAt(jTableRelatos.getSelectedRow(), 3);
        jTextAreaDescricao.setText(descricao);

        if (situacao.equals("SIM")) {
            jRadioButtonSituacaoSim.setSelected(true);
        } else {
            jRadioButtonSituacaoNao.setSelected(true);
        }
        jButtonInserirRelato.setEnabled(false);
        jButtonAtualizarRelato.setEnabled(true);

    }//GEN-LAST:event_jTableRelatosMouseClicked
    public void preencheUsuario(String sql) {
        try {
            con.excutaSQL(sql);
            con.rs.first();
            jLabelCod.setText("" + con.rs.getInt("id_usuario"));
            jTextFieldNome.setText(con.rs.getString("nome_usuario"));
            jTextFieldCpf.setText(con.rs.getString("cpf"));
            jTextFieldRg.setText(con.rs.getString("rg"));
            jTextFieldNis.setText(con.rs.getString("nis"));
            String sexo = con.rs.getString("sexo");
            if (sexo.equals("MASCULINO")) {
                jRadioButtonMasculino.setSelected(true);
            } else {
                jRadioButtonFeminino.setSelected(true);
            }
            
            String data = con.rs.getString("data_nascimento");
            try {
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(data);
                jDateChooserDataNascimento.setDate(date);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

            String sabe_ler = con.rs.getString("sabe_ler");
            if (sabe_ler.equals("SIM")) {
                jRadioButtonSabeSim.setSelected(true);
            } else {
                jRadioButtonSabeNao.setSelected(true);
            }
            String frequenta_escola = con.rs.getString("frequenta_escola");
            if (frequenta_escola.equals("SIM")) {
                jRadioButtonFrequentaSim.setSelected(true);
            } else {
                jRadioButtonFrequentaNao.setSelected(true);
            }
            String escolaridade = con.rs.getString("escolaridade");
            jComboBoxEscolaridade.setSelectedItem(escolaridade);
            String possui_ctps = con.rs.getString("possui_ctps");
            if (possui_ctps.equals("SIM")) {
                jRadioButtonPossuiSim.setSelected(true);
            } else {
                jRadioButtonPossuiNao.setSelected(true);
            }
            String condicao_ocupacao = con.rs.getString("condicao_ocupacao");
            jComboBoxCondicao.setSelectedItem(condicao_ocupacao);
            jTextFieldQualificao.setText(con.rs.getString("qualificacao_profissional"));
            jTextFieldRendaMensal.setText(String.valueOf(con.rs.getDouble("renda_mensal")));
            jTextFieldBairro.setText(con.rs.getString("bairro"));
            jTextFieldEndereco.setText(con.rs.getString("endereco"));
            jTextFieldNumero.setText(con.rs.getString("numero"));

        } catch (SQLException ex) {
            Logger.getLogger(jfrmRegistroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void preencherTabelaConsultaUsuario(String sql) throws SQLException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD", "NOME", "CPF", "RG", "NIS"};
        con.excutaSQL(sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("id_usuario"), con.rs.getString("nome_usuario"), con.rs.getString("cpf"), con.rs.getString("rg"), con.rs.getString("nis")});
            } while (con.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "USUARIO NAO ENCONTRADO");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTablePesquisaUsuario.setModel(modelo);
        jTablePesquisaUsuario.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTablePesquisaUsuario.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisaUsuario.getColumnModel().getColumn(1).setPreferredWidth(350);
        jTablePesquisaUsuario.getColumnModel().getColumn(1).setResizable(false);
        jTablePesquisaUsuario.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTablePesquisaUsuario.getColumnModel().getColumn(2).setResizable(false);
        jTablePesquisaUsuario.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTablePesquisaUsuario.getColumnModel().getColumn(3).setResizable(false);
        jTablePesquisaUsuario.getColumnModel().getColumn(4).setPreferredWidth(135);
        jTablePesquisaUsuario.getColumnModel().getColumn(4).setResizable(false);
        jTablePesquisaUsuario.getTableHeader().setReorderingAllowed(false);
        jTablePesquisaUsuario.setAutoResizeMode(jTablePesquisaUsuario.AUTO_RESIZE_OFF);
        jTablePesquisaUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void preencherTabelaDeficiencia(String sql) throws SQLException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD", "DEFICIENCIA", "CUIDADOR"};
        con.excutaSQL(sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("id_usuario_deficiencia"), con.rs.getString("nome_deficiencia"), con.rs.getString("cuidador")});
            } while (con.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SEM DEFICIENCIAS CADASTRADAS");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableDeficiencia.setModel(modelo);
        jTableDeficiencia.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableDeficiencia.getColumnModel().getColumn(0).setResizable(false);
        jTableDeficiencia.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTableDeficiencia.getColumnModel().getColumn(1).setResizable(false);
        jTableDeficiencia.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTableDeficiencia.getColumnModel().getColumn(2).setResizable(false);
        jTableDeficiencia.getTableHeader().setReorderingAllowed(false);
        jTableDeficiencia.setAutoResizeMode(jTableDeficiencia.AUTO_RESIZE_OFF);
        jTableDeficiencia.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void preencherTabelaRelato(String sql) throws SQLException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD", "RELATO", "DESCRICAO", "PERSISTE?", "REGISTRO"};
        con.excutaSQL(sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("id_usuario_relato"), con.rs.getString("relato"), con.rs.getString("descricao"), con.rs.getString("situacao_persiste"), con.rs.getString("data_relato")});
            } while (con.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SEM RELATOS CADASTRADOS");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableRelatos.setModel(modelo);
        jTableRelatos.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableRelatos.getColumnModel().getColumn(0).setResizable(false);
        jTableRelatos.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTableRelatos.getColumnModel().getColumn(1).setResizable(false);
        jTableRelatos.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTableRelatos.getColumnModel().getColumn(2).setResizable(false);
        jTableRelatos.getColumnModel().getColumn(3).setPreferredWidth(85);
        jTableRelatos.getColumnModel().getColumn(3).setResizable(false);
        jTableRelatos.getColumnModel().getColumn(4).setPreferredWidth(85);
        jTableRelatos.getColumnModel().getColumn(4).setResizable(false);
        jTableRelatos.getTableHeader().setReorderingAllowed(false);
        jTableRelatos.setAutoResizeMode(jTableRelatos.AUTO_RESIZE_OFF);
        jTableRelatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmRegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButtonAtualizarRelato;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonInserirRelato;
    private javax.swing.JButton jButtonInserirSaude;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCondicao;
    private javax.swing.JComboBox<String> jComboBoxDeficiencia;
    private javax.swing.JComboBox<String> jComboBoxEscolaridade;
    private javax.swing.JComboBox<String> jComboBoxRelato;
    private com.toedter.calendar.JDateChooser jDateChooserDataNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonFeminino;
    private javax.swing.JRadioButton jRadioButtonFrequentaNao;
    private javax.swing.JRadioButton jRadioButtonFrequentaSim;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JRadioButton jRadioButtonPossuiNao;
    private javax.swing.JRadioButton jRadioButtonPossuiSim;
    private javax.swing.JRadioButton jRadioButtonSabeNao;
    private javax.swing.JRadioButton jRadioButtonSabeSim;
    private javax.swing.JRadioButton jRadioButtonSituacaoNao;
    private javax.swing.JRadioButton jRadioButtonSituacaoSim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPanePesquisa;
    private javax.swing.JTable jTableDeficiencia;
    private javax.swing.JTable jTablePesquisaUsuario;
    private javax.swing.JTable jTableRelatos;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldConsultaUsuario;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldCuidador;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNis;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldQualificao;
    private javax.swing.JTextField jTextFieldRendaMensal;
    private javax.swing.JTextField jTextFieldRg;
    // End of variables declaration//GEN-END:variables
}
