/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Conexao;
import Controle.ControleFamilia;
import Controle.ControleUsuario;
import Controle.ModeloTabela;
import Modelo.ModeloFamilia;
import Modelo.ModeloUsuario;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Matheus Moura
 */
public class jfrmCadastroFamilia extends javax.swing.JFrame {

    private Conexao con = new Conexao();
    private int id_familia;
    private int id_usuario = 0;
    private int flag = 0;
    private Timestamp dataDeHoje = new Timestamp(System.currentTimeMillis());

    /**
     * Creates new form jfrmManterFamilia
     */
    public jfrmCadastroFamilia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxParentesco = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableComposicaoFamiliar = new javax.swing.JTable();
        jButtonInserirUsuario = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuarioVinculados = new javax.swing.JTable();
        jComboBoxEspecificidade = new javax.swing.JComboBox<>();
        jTextFieldUsuario1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabelCod = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonResPropria = new javax.swing.JRadioButton();
        jRadioButtonResAlugada = new javax.swing.JRadioButton();
        jRadioButtonResCedida = new javax.swing.JRadioButton();
        jRadioButtonResOcupada = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonMatAlve = new javax.swing.JRadioButton();
        jRadioButtonMatMadeira = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonAcessoEnerSim = new javax.swing.JRadioButton();
        jRadioButtonAcessoEnerNao = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonAguaSim = new javax.swing.JRadioButton();
        jRadioButtonAguaNao = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonAbastecimentoRede = new javax.swing.JRadioButton();
        jRadioButtonAbastecimentoPoco = new javax.swing.JRadioButton();
        jRadioButtonAbastecimentoCisterna = new javax.swing.JRadioButton();
        jRadioButtonAbastecimentoCarro = new javax.swing.JRadioButton();
        jRadioButtonAbastecimentoOutro = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonColetaSim = new javax.swing.JRadioButton();
        jRadioButtonColetaNao = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonZonaSim = new javax.swing.JRadioButton();
        jRadioButtonZonaNao = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonAcessoGeoNao = new javax.swing.JRadioButton();
        jRadioButtonAcesoGeoSim = new javax.swing.JRadioButton();
        jRadioButtonViolenciaSim = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonViolenciaNao = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxBeneficio = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jDateChooserRecebimento = new com.toedter.calendar.JDateChooser();
        jButtonInserirBeneficio = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBeneficio = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jDateChooserIngresso = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jDateChooserDesligamento = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxServicoPrograma = new javax.swing.JComboBox<>();
        jButtonInserirServicoPrograma = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableServicoPrograma = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovaFamilia = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CADASTRO DE FAMILIAS");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ESPECIFICIDADES SOCIAIS, ETNICAS OU CULTURAIS DA FAMILIA");
        jLabel10.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("COMPOSICAO FAMILIAR");
        jLabel11.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jComboBoxParentesco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01 - PESSOA DE REFERENCIA", "02 - PAI", "03 - MAE", "04 - FILHA(O)", "05 - IRMA(O)", "06 - AVO", "07 - NETA(O)", "08 -TIA(O)", "09 - SOBRINHA(O)", "10 - BISAVO", "11 - BISNETA(O)", "12 - PRIMA(O)", "13 - SOGRA(O)", "14 - GENRO", "15 - NORA", "16 - PADRASTO", "17 - MADRASTA", "18 - ENTEADO", "19 - CONJUGUE", "20 - OUTROS" }));
        jComboBoxParentesco.setEnabled(false);

        jTableComposicaoFamiliar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableComposicaoFamiliar.setEnabled(false);
        jTableComposicaoFamiliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableComposicaoFamiliarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableComposicaoFamiliar);

        jButtonInserirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/business_application_addthedatabase_add_insert_database_db_2313.png"))); // NOI18N
        jButtonInserirUsuario.setText("INSERIR");
        jButtonInserirUsuario.setEnabled(false);
        jButtonInserirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirUsuarioActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("USUARIOS VINCULADOS A FAMILIA");
        jLabel12.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTableUsuarioVinculados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableUsuarioVinculados.setEnabled(false);
        jScrollPane2.setViewportView(jTableUsuarioVinculados);

        jComboBoxEspecificidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1 - FAMILIA/PESSOA EM SITUACAO DE RUA", "2 - FAMILIA QUILOMBOLA", "3 - FAMILIA RIBEIRINHA", "4 - FAMILIA CIGANA", "5 - FAMILIA INDIGENA RESIDENTE EM ALDEIA/RESERVA", "6 - FAMILIA INDIGENA NAO RESIDENTE EM ALDEIA/RESERVA", "99 - OUTRAS" }));
        jComboBoxEspecificidade.setEnabled(false);

        jTextFieldUsuario1.setEnabled(false);
        jTextFieldUsuario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldUsuario1KeyReleased(evt);
            }
        });

        jLabel14.setText("CODIGO FAMILIA:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTextFieldUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBoxParentesco, 0, 295, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 688, Short.MAX_VALUE)
                        .addComponent(jButtonInserirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxEspecificidade, 0, 808, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCod, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEspecificidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInserirUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DADOS GERAIS", jPanel3);

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("TIPO DE RESIDENCIA");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(jRadioButtonResPropria);
        jRadioButtonResPropria.setSelected(true);
        jRadioButtonResPropria.setText("PROPRIA");
        jRadioButtonResPropria.setEnabled(false);
        jRadioButtonResPropria.setOpaque(false);

        buttonGroup1.add(jRadioButtonResAlugada);
        jRadioButtonResAlugada.setText("ALUGADA");
        jRadioButtonResAlugada.setEnabled(false);
        jRadioButtonResAlugada.setOpaque(false);

        buttonGroup1.add(jRadioButtonResCedida);
        jRadioButtonResCedida.setText("CEDIDA");
        jRadioButtonResCedida.setEnabled(false);
        jRadioButtonResCedida.setOpaque(false);

        buttonGroup1.add(jRadioButtonResOcupada);
        jRadioButtonResOcupada.setText("OCUPADA");
        jRadioButtonResOcupada.setEnabled(false);
        jRadioButtonResOcupada.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("MATERIAL DAS PAREDES EXTERNAS DO DOMICILIO");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup2.add(jRadioButtonMatAlve);
        jRadioButtonMatAlve.setSelected(true);
        jRadioButtonMatAlve.setText("ALVENARIA OU MADEIRA APARELHADA");
        jRadioButtonMatAlve.setEnabled(false);
        jRadioButtonMatAlve.setOpaque(false);

        buttonGroup2.add(jRadioButtonMatMadeira);
        jRadioButtonMatMadeira.setText("MADEIRA APROVEITADA, TAIPA OU OUTROS MATEIRAIS PRECAREIOS");
        jRadioButtonMatMadeira.setEnabled(false);
        jRadioButtonMatMadeira.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("ACESSO A ENERGIA ELETRICA");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup3.add(jRadioButtonAcessoEnerSim);
        jRadioButtonAcessoEnerSim.setSelected(true);
        jRadioButtonAcessoEnerSim.setText("SIM");
        jRadioButtonAcessoEnerSim.setEnabled(false);
        jRadioButtonAcessoEnerSim.setOpaque(false);

        buttonGroup3.add(jRadioButtonAcessoEnerNao);
        jRadioButtonAcessoEnerNao.setText("NAO");
        jRadioButtonAcessoEnerNao.setEnabled(false);
        jRadioButtonAcessoEnerNao.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("AGUA CANALIZADA");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup4.add(jRadioButtonAguaSim);
        jRadioButtonAguaSim.setSelected(true);
        jRadioButtonAguaSim.setText("SIM");
        jRadioButtonAguaSim.setEnabled(false);
        jRadioButtonAguaSim.setOpaque(false);

        buttonGroup4.add(jRadioButtonAguaNao);
        jRadioButtonAguaNao.setText("NAO");
        jRadioButtonAguaNao.setEnabled(false);
        jRadioButtonAguaNao.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("FORMA DE ABASTECIMENTO DE AGUA");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup5.add(jRadioButtonAbastecimentoRede);
        jRadioButtonAbastecimentoRede.setSelected(true);
        jRadioButtonAbastecimentoRede.setText("REDE GERAL DE DISTRIBUICAO");
        jRadioButtonAbastecimentoRede.setEnabled(false);
        jRadioButtonAbastecimentoRede.setOpaque(false);

        buttonGroup5.add(jRadioButtonAbastecimentoPoco);
        jRadioButtonAbastecimentoPoco.setText("POCO OU NASCENTE");
        jRadioButtonAbastecimentoPoco.setEnabled(false);
        jRadioButtonAbastecimentoPoco.setOpaque(false);

        buttonGroup5.add(jRadioButtonAbastecimentoCisterna);
        jRadioButtonAbastecimentoCisterna.setText("CISTERNA DE CAPTACAO DE AGUA DA CHUVA");
        jRadioButtonAbastecimentoCisterna.setEnabled(false);
        jRadioButtonAbastecimentoCisterna.setOpaque(false);

        buttonGroup5.add(jRadioButtonAbastecimentoCarro);
        jRadioButtonAbastecimentoCarro.setText("CARRO PIPA");
        jRadioButtonAbastecimentoCarro.setEnabled(false);
        jRadioButtonAbastecimentoCarro.setOpaque(false);

        buttonGroup5.add(jRadioButtonAbastecimentoOutro);
        jRadioButtonAbastecimentoOutro.setText("OUTRO");
        jRadioButtonAbastecimentoOutro.setEnabled(false);
        jRadioButtonAbastecimentoOutro.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("COLETA DE LIXO");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup6.add(jRadioButtonColetaSim);
        jRadioButtonColetaSim.setSelected(true);
        jRadioButtonColetaSim.setText("SIM");
        jRadioButtonColetaSim.setEnabled(false);
        jRadioButtonColetaSim.setOpaque(false);

        buttonGroup6.add(jRadioButtonColetaNao);
        jRadioButtonColetaNao.setText("NAO");
        jRadioButtonColetaNao.setEnabled(false);
        jRadioButtonColetaNao.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("ZONA DE RISCO OU DESABAMENTO");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup7.add(jRadioButtonZonaSim);
        jRadioButtonZonaSim.setSelected(true);
        jRadioButtonZonaSim.setText("SIM");
        jRadioButtonZonaSim.setEnabled(false);
        jRadioButtonZonaSim.setOpaque(false);

        buttonGroup7.add(jRadioButtonZonaNao);
        jRadioButtonZonaNao.setText("NAO");
        jRadioButtonZonaNao.setEnabled(false);
        jRadioButtonZonaNao.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("DIFICIL ACESSO GEOGRAFICO");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup8.add(jRadioButtonAcessoGeoNao);
        jRadioButtonAcessoGeoNao.setText("NAO");
        jRadioButtonAcessoGeoNao.setEnabled(false);
        jRadioButtonAcessoGeoNao.setOpaque(false);

        buttonGroup8.add(jRadioButtonAcesoGeoSim);
        jRadioButtonAcesoGeoSim.setSelected(true);
        jRadioButtonAcesoGeoSim.setText("SIM");
        jRadioButtonAcesoGeoSim.setEnabled(false);
        jRadioButtonAcesoGeoSim.setOpaque(false);

        buttonGroup9.add(jRadioButtonViolenciaSim);
        jRadioButtonViolenciaSim.setSelected(true);
        jRadioButtonViolenciaSim.setText("SIM");
        jRadioButtonViolenciaSim.setEnabled(false);
        jRadioButtonViolenciaSim.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("AREA COM FORTE PRESENCA DE VIOLENCIA");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup9.add(jRadioButtonViolenciaNao);
        jRadioButtonViolenciaNao.setText("NAO");
        jRadioButtonViolenciaNao.setEnabled(false);
        jRadioButtonViolenciaNao.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonAbastecimentoRede)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAbastecimentoPoco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAbastecimentoCisterna)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAbastecimentoCarro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonZonaSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonZonaNao))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonAcesoGeoSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAcessoGeoNao))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonViolenciaSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonViolenciaNao)))
                        .addGap(0, 174, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonResPropria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonResAlugada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonResCedida)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonResOcupada))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonAcessoEnerSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonAcessoEnerNao))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonMatAlve)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonMatMadeira))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonAguaSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonAguaNao))
                                    .addComponent(jRadioButtonAbastecimentoOutro)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonColetaSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonColetaNao)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonResPropria)
                    .addComponent(jRadioButtonResAlugada)
                    .addComponent(jRadioButtonResCedida)
                    .addComponent(jRadioButtonResOcupada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMatAlve)
                    .addComponent(jRadioButtonMatMadeira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAcessoEnerSim)
                    .addComponent(jRadioButtonAcessoEnerNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAguaSim)
                    .addComponent(jRadioButtonAguaNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAbastecimentoRede)
                    .addComponent(jRadioButtonAbastecimentoPoco)
                    .addComponent(jRadioButtonAbastecimentoCisterna)
                    .addComponent(jRadioButtonAbastecimentoCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonAbastecimentoOutro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonColetaSim)
                    .addComponent(jRadioButtonColetaNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonZonaSim)
                    .addComponent(jRadioButtonZonaNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAcesoGeoSim)
                    .addComponent(jRadioButtonAcessoGeoNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonViolenciaSim)
                    .addComponent(jRadioButtonViolenciaNao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HABITACAO", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setText("BENEFICIO");
        jLabel19.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jComboBoxBeneficio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01 - AUXILIO NATALIDADE", "02 - AUXILIO FUNERAL", "03 - ITEM/KIT ESPECIFICO PARA ENFRENTAMENTO DE SITUAÇOES DE EMERGENCIA OU CALAMIDADE PUBLICA", "04 - CESTA BASICA", "05 - ALUGUEL SOCIAL/PAGAMENTO DE ALUGUEL", "06 - BPC", "99 - OUTROS" }));
        jComboBoxBeneficio.setEnabled(false);

        jLabel17.setText("DATA DE RECEBIMENTO");
        jLabel17.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jDateChooserRecebimento.setEnabled(false);

        jButtonInserirBeneficio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/business_application_addthedatabase_add_insert_database_db_2313.png"))); // NOI18N
        jButtonInserirBeneficio.setText("Inserir");
        jButtonInserirBeneficio.setEnabled(false);
        jButtonInserirBeneficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirBeneficioActionPerformed(evt);
            }
        });

        jLabel20.setText("BENEFICIOS RECEBIDOS PELA FAMILIA");
        jLabel20.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTableBeneficio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableBeneficio.setEnabled(false);
        jScrollPane3.setViewportView(jTableBeneficio);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxBeneficio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonInserirBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jDateChooserRecebimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 683, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInserirBeneficio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("BENEFICIOS", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setText("DATA DE INGRESSO");
        jLabel27.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jDateChooserIngresso.setEnabled(false);

        jLabel18.setText("DATA DE DESLIGAMENTO");
        jLabel18.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jDateChooserDesligamento.setEnabled(false);

        jLabel21.setText("SERVICO/PROGRAMA");
        jLabel21.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jComboBoxServicoPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01 - SERVIÇO DE CONVIVENCIA E FORTALECIMENTO DE VINCULOS PARA CRIANÇAS E/ OU ADOLESCENTES", "02 - SERVIÇO DE CONVIVENCIA E FORTALECIMENTO DE VINCULOS PARA IDOSOS", "03 - GRUPO ESPECIFICO DESENVOLVIDO PELO PAIF", "04 - GRUPO ESPECIFICO DESENVOLVIDO PELO PAEFI", "05 - PROGRAMAS OU PROJETOS ESPECIFICOS DA ASSISTENCIA SOCIAL QUE NAO CONFIGUREM SERVICOS CONTINUADOS", "06 - PROGRAMAS OU PROJETOS DE OUTRAS POLITICAS SETORIAIS (EDUCACAO, ESPORTE, CULTURA ETC)", "07 - PROGRAMA BOLSA FAMILIA", "08 - TARIFA SOCIAL DE ENERGIA ELETRICA", "09 - PROGRAMA MINHA CASA MINHA VIDA", "10 - APOSENTADORIA PARA PESSOAS DE BAIXA RENDA", "11 - PROGRAMA NACIONAL DE REFORMA AGRARIA", "12 - PROGRAMA NACIONAL DE CREDITO FUNDIARIO", "13 - POPULAÇAO EM SITUAÇAO DE RUA", "14 - BPC NA ESCOLA", "16 - BPC TRABALHO", "16 - ACESSUAS TRABALHO", "99 - OUTROS" }));
        jComboBoxServicoPrograma.setEnabled(false);

        jButtonInserirServicoPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/business_application_addthedatabase_add_insert_database_db_2313.png"))); // NOI18N
        jButtonInserirServicoPrograma.setText("INSERIR");
        jButtonInserirServicoPrograma.setEnabled(false);
        jButtonInserirServicoPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirServicoProgramaActionPerformed(evt);
            }
        });

        jLabel22.setText("SERVICOS OU PROGRAMAS UTILIZADOS PELO USUARIO");
        jLabel22.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jTableServicoPrograma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableServicoPrograma.setEnabled(false);
        jScrollPane4.setViewportView(jTableServicoPrograma);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxServicoPrograma, 0, 808, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserIngresso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserDesligamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonInserirServicoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(25, 25, 25))
                    .addComponent(jDateChooserDesligamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(4, 4, 4)
                .addComponent(jComboBoxServicoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInserirServicoPrograma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SERVICOS E PROGRAMAS", jPanel5);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/savedisk_floppydisk_guardar_1543.png"))); // NOI18N
        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonNovaFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N
        jButtonNovaFamilia.setText("NOVO");
        jButtonNovaFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaFamiliaActionPerformed(evt);
            }
        });

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel_stop_exit_1583 (1).png"))); // NOI18N
        jButton15.setText("CANCELAR");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNovaFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton15, jButtonSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addComponent(jButtonNovaFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton15, jButtonSalvar});

        setSize(new java.awt.Dimension(849, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void habilitaTexto() {
        jComboBoxEspecificidade.setEnabled(true);
        jComboBoxBeneficio.setEnabled(true);
        jComboBoxServicoPrograma.setEnabled(true);
        jTableComposicaoFamiliar.setEnabled(true);
        jTableUsuarioVinculados.setEnabled(true);
        jTableBeneficio.setEnabled(true);
        jTableServicoPrograma.setEnabled(true);
        jTextFieldUsuario1.setEnabled(true);
        jRadioButtonAguaNao.setEnabled(true);
        jRadioButtonAguaSim.setEnabled(true);
        jRadioButtonColetaNao.setEnabled(true);
        jRadioButtonColetaSim.setEnabled(true);
        jRadioButtonMatAlve.setEnabled(true);
        jRadioButtonMatMadeira.setEnabled(true);
        jRadioButtonResAlugada.setEnabled(true);
        jRadioButtonResCedida.setEnabled(true);
        jRadioButtonResOcupada.setEnabled(true);
        jRadioButtonResPropria.setEnabled(true);
        jRadioButtonViolenciaNao.setEnabled(true);
        jRadioButtonViolenciaSim.setEnabled(true);
        jRadioButtonZonaNao.setEnabled(true);
        jRadioButtonZonaSim.setEnabled(true);
        jRadioButtonResAlugada.setEnabled(true);
        jRadioButtonResCedida.setEnabled(true);
        jRadioButtonResOcupada.setEnabled(true);
        jRadioButtonResPropria.setEnabled(true);
        jRadioButtonAbastecimentoCarro.setEnabled(true);
        jRadioButtonAbastecimentoCisterna.setEnabled(true);
        jRadioButtonAbastecimentoOutro.setEnabled(true);
        jRadioButtonAbastecimentoPoco.setEnabled(true);
        jRadioButtonAbastecimentoRede.setEnabled(true);
        jRadioButtonAcessoEnerSim.setEnabled(true);
        jRadioButtonAcessoEnerNao.setEnabled(true);
        jButtonInserirBeneficio.setEnabled(true);
        jRadioButtonAcesoGeoSim.setEnabled(true);
        jRadioButtonAcessoGeoNao.setEnabled(true);
        jRadioButtonAcessoEnerNao.setEnabled(true);
        jButtonInserirServicoPrograma.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonInserirUsuario.setEnabled(true);
        jDateChooserDesligamento.setEnabled(true);
        jDateChooserIngresso.setEnabled(true);
        jDateChooserRecebimento.setEnabled(true);
    }

    private void desabilitaTexto() {
        jComboBoxEspecificidade.setEnabled(false);
        jComboBoxBeneficio.setEnabled(false);
        jComboBoxParentesco.setEnabled(false);
        jComboBoxServicoPrograma.setEnabled(false);
        jTableComposicaoFamiliar.setEnabled(false);
        jTableUsuarioVinculados.setEnabled(false);
        jTableBeneficio.setEnabled(false);
        jTableServicoPrograma.setEnabled(false);
        jTextFieldUsuario1.setEnabled(false);
        jRadioButtonAguaNao.setEnabled(false);
        jRadioButtonAguaSim.setEnabled(false);
        jRadioButtonColetaNao.setEnabled(false);
        jRadioButtonColetaSim.setEnabled(false);
        jRadioButtonMatAlve.setEnabled(false);
        jRadioButtonMatMadeira.setEnabled(false);
        jRadioButtonResAlugada.setEnabled(false);
        jRadioButtonResCedida.setEnabled(false);
        jRadioButtonResOcupada.setEnabled(false);
        jRadioButtonResPropria.setEnabled(false);
        jRadioButtonViolenciaNao.setEnabled(false);
        jRadioButtonViolenciaSim.setEnabled(false);
        jRadioButtonZonaNao.setEnabled(false);
        jRadioButtonZonaSim.setEnabled(false);
        jButtonInserirBeneficio.setEnabled(false);
        jButtonInserirServicoPrograma.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonInserirUsuario.setEnabled(false);
        jDateChooserDesligamento.setEnabled(false);
        jDateChooserIngresso.setEnabled(false);
        jDateChooserRecebimento.setEnabled(false);
        jRadioButtonAcessoEnerSim.setEnabled(false);
        jRadioButtonAcessoEnerNao.setEnabled(false);
        jRadioButtonAbastecimentoCarro.setEnabled(false);
        jRadioButtonAbastecimentoCisterna.setEnabled(false);
        jRadioButtonAbastecimentoOutro.setEnabled(false);
        jRadioButtonAbastecimentoPoco.setEnabled(false);
        jRadioButtonAbastecimentoRede.setEnabled(false);
        jRadioButtonAcessoEnerSim.setEnabled(false);
        jRadioButtonAcessoEnerNao.setEnabled(false);
        jRadioButtonAcessoGeoNao.setEnabled(false);
        jRadioButtonAcesoGeoSim.setEnabled(false);

    }

    private void limpaTexto() {
        jLabelCod.setText("");
        jTextFieldUsuario1.setText("");
        jComboBoxBeneficio.setSelectedIndex(0);
        jComboBoxEspecificidade.setSelectedIndex(0);
        jComboBoxParentesco.setSelectedIndex(0);
        jComboBoxServicoPrograma.setSelectedIndex(0);
        jRadioButtonAcesoGeoSim.setSelected(true);
        jRadioButtonResPropria.setSelected(true);
        jRadioButtonMatAlve.setSelected(true);
        jRadioButtonAcessoEnerSim.setSelected(true);
        jRadioButtonAbastecimentoRede.setSelected(true);
        jRadioButtonColetaSim.setSelected(true);
        jRadioButtonZonaSim.setSelected(true);
        jRadioButtonAcesoGeoSim.setSelected(true);
        jRadioButtonViolenciaSim.setSelected(true);

    }
    
    private String getDataSistema() {
        Timestamp dataDeHoje = new Timestamp(System.currentTimeMillis());
        return "" + dataDeHoje + " - " + System.getProperty("login");
    }
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       
        if (jTableUsuarioVinculados.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "VERIFICAR OS CAMPOS!\n1 - A FAMILIA DEVE CONTER USUARIOS");
        } else {
            ModeloFamilia modFamilia = new ModeloFamilia();
            modFamilia.setEspecificidade(String.valueOf(jComboBoxEspecificidade.getSelectedItem()));

            if (jRadioButtonResPropria.isSelected()) {
                modFamilia.setTipo_residencia("PROPRIA");
            } else {
            }
            if (jRadioButtonResCedida.isSelected()) {
                modFamilia.setTipo_residencia("CEDIDA");
            } else {
            }
            if (jRadioButtonResOcupada.isSelected()) {
                modFamilia.setTipo_residencia("OCUPADA");
            } else {
            }
            if (jRadioButtonResAlugada.isSelected()) {
                modFamilia.setTipo_residencia("ALUGADA");
            }

            if (jRadioButtonMatAlve.isSelected()) {
                modFamilia.setMaterial_parede("ALVENARIA OU MADEIRA APARELHADA");
            } else {
            }
            if (jRadioButtonMatMadeira.isSelected()) {
                modFamilia.setMaterial_parede("MADEIRA APROVEITADA, TAIPA OU OUTROS MATEIRAIS PRECAREIOS");
            }

            if (jRadioButtonAcessoEnerSim.isSelected()) {
                modFamilia.setAcesso_energia("SIM");
            } else {
            }
            if (jRadioButtonAcessoEnerNao.isSelected()) {
                modFamilia.setAcesso_energia("NAO");
            }

            if (jRadioButtonAguaSim.isSelected()) {
                modFamilia.setAgua_canalizada("SIM");
            } else {
            }
            if (jRadioButtonAguaNao.isSelected()) {
                modFamilia.setAgua_canalizada("NAO");
            }

            if (jRadioButtonAbastecimentoCarro.isSelected()) {
                modFamilia.setAbastecimento_agua("CARRO PIPA");
            } else {
            }
            if (jRadioButtonAbastecimentoCisterna.isSelected()) {
                modFamilia.setAbastecimento_agua("CISTERNA DE CAPTACAO DE AGUA DE CHUVA");
            } else {
            }
            if (jRadioButtonAbastecimentoOutro.isSelected()) {
                modFamilia.setAbastecimento_agua("OUTRO");
            } else {
            }
            if (jRadioButtonAbastecimentoPoco.isSelected()) {
                modFamilia.setAbastecimento_agua("POCO OU NASCENTE");
            } else {
            }
            if (jRadioButtonAbastecimentoRede.isSelected()) {
                modFamilia.setAbastecimento_agua("REDE GERAL DE DISTRIBUICAO");
            }

            if (jRadioButtonColetaSim.isSelected()) {
                modFamilia.setColeta_lixo("SIM");
            } else {
            }
            if (jRadioButtonColetaNao.isSelected()) {
                modFamilia.setColeta_lixo("NAO");
            }

            if (jRadioButtonZonaSim.isSelected()) {
                modFamilia.setZona_risco("SIM");
            } else {
            }
            if (jRadioButtonZonaNao.isSelected()) {
                modFamilia.setZona_risco("NAO");
            }

            if (jRadioButtonAcesoGeoSim.isSelected()) {
                modFamilia.setDificil_acesso("SIM");
            } else {
            }
            if (jRadioButtonAcessoGeoNao.isSelected()) {
                modFamilia.setDificil_acesso("NAO");
            }

            if (jRadioButtonViolenciaSim.isSelected()) {
                modFamilia.setPresenca_violencia("SIM");
            } else {
            }
            if (jRadioButtonViolenciaNao.isSelected()) {
                modFamilia.setPresenca_violencia("NAO");
            }

            modFamilia.setUltimo_registro(getDataSistema());
            modFamilia.setId_familia(id_familia);

            ControleFamilia controlFamilia = new ControleFamilia();
            controlFamilia.AtualizarFamilia(modFamilia);

            dispose();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if (jLabelCod.getText().trim().isEmpty()) {
            dispose();
        } else {
            ModeloFamilia modFamilia = new ModeloFamilia();
            modFamilia.setId_familia(id_familia);
            ControleFamilia controleFamilia = new ControleFamilia();
            controleFamilia.DeletaFamiliaUsuario(modFamilia);
            controleFamilia.DeletaFamiliaBeneficio(modFamilia);
            controleFamilia.DeletaFamiliaServico(modFamilia);
            controleFamilia.DeletaFamilia(modFamilia);
            dispose();
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButtonNovaFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaFamiliaActionPerformed
        ModeloFamilia modFamilia = new ModeloFamilia();
        modFamilia.setEspecificidade("");
        ControleFamilia controlfFamilia = new ControleFamilia();
        controlfFamilia.InserirFamilia(modFamilia);
        jComboBoxParentesco.setSelectedIndex(1);
        try {
            con.conectar();
            con.excutaSQL("select * from fastflowcreas.familia");
            con.rs.last();
            id_familia = con.rs.getInt("id_familia");
            jLabelCod.setText("" + id_familia);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(jfrmCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        habilitaTexto();
        jButtonNovaFamilia.setEnabled(false);
    }//GEN-LAST:event_jButtonNovaFamiliaActionPerformed

    private void jTextFieldUsuario1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuario1KeyReleased
        try {
            preencherTabelaComposicaoFamiliar("select * from fastflowcreas.usuario where nome_usuario like '%" + jTextFieldUsuario1.getText().toUpperCase() + "%'");
        } catch (SQLException ex) {
            Logger.getLogger(jfrmCadastroFamilia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldUsuario1KeyReleased

    private void jButtonInserirBeneficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirBeneficioActionPerformed

        ModeloFamilia modFamilia = new ModeloFamilia();
        modFamilia.setId_familia(id_familia);
        modFamilia.setBeneficio(String.valueOf(jComboBoxBeneficio.getSelectedItem()));
        modFamilia.setUltimo_registro(getDataSistema());
       
        if (jDateChooserRecebimento.getDate() == null) {
            modFamilia.setData_recebimento(null);
        } else {
            java.util.Date pegaReceb = jDateChooserRecebimento.getDate();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String data = formato.format(pegaReceb);
            modFamilia.setData_recebimento(data);
        }

        if (jComboBoxBeneficio.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "INFORME O BENEFICIO ANTES DE INSERIR!");
        } else {
            ControleFamilia controlFamilia = new ControleFamilia();
            controlFamilia.InserirFamiliaBeneficio(modFamilia);
            jComboBoxBeneficio.setSelectedIndex(0);

            try {
                preencherTabelaBeneficio("select * from fastflowcreas.familia_beneficio where id_familia =" + id_familia +"order by data_recebimento");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButtonInserirBeneficioActionPerformed
    
    private int verificaCamposFamilia() {
        if (jLabelCod.getText().trim().isEmpty() || id_usuario == 0 || jTextFieldUsuario1.getText().trim().isEmpty()) {
            return 0;
        } else {
            return 1;
        }
    }
    
    private void jButtonInserirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirUsuarioActionPerformed
        ModeloFamilia modFamilia = new ModeloFamilia();
        modFamilia.setId_familia(id_familia);
        modFamilia.setId_usuario(id_usuario);
        modFamilia.setParentesco(String.valueOf(jComboBoxParentesco.getSelectedItem()));
        if (verificaCamposFamilia() == 0) {
            JOptionPane.showMessageDialog(null, "INFORME O USUARIO A SER VINCULADO!");
        } else {
            ControleFamilia controlFamilia = new ControleFamilia();
            if (controlFamilia.InserirFamiliaUsuario(modFamilia) == 0) {
                jTextFieldUsuario1.setText("");
                jComboBoxParentesco.setSelectedIndex(0);
                jComboBoxParentesco.setEnabled(true);
                try {
                    preencherTabelaUsuarioVinculado("SELECT * FROM fastflowcreas.familia_usuario, fastflowcreas.usuario where fastflowcreas.familia_usuario.id_usuario =fastflowcreas.usuario.id_usuario and fastflowcreas.familia_usuario.id_familia = " + id_familia + " order by parentesco");
                } catch (SQLException ex) {
                    Logger.getLogger(jfrmCadastroFamilia.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                jTextFieldUsuario1.setText("");
            }
        }
    }//GEN-LAST:event_jButtonInserirUsuarioActionPerformed

    private void jTableComposicaoFamiliarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableComposicaoFamiliarMouseClicked
        id_usuario = Integer.parseInt("" + jTableComposicaoFamiliar.getValueAt(jTableComposicaoFamiliar.getSelectedRow(), 0));
        String nome_usuario = "" + jTableComposicaoFamiliar.getValueAt(jTableComposicaoFamiliar.getSelectedRow(), 1);
        jTextFieldUsuario1.setText("" + id_usuario + "-" + nome_usuario);

    }//GEN-LAST:event_jTableComposicaoFamiliarMouseClicked

    private void jButtonInserirServicoProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirServicoProgramaActionPerformed
        ModeloFamilia modFamilia = new ModeloFamilia();
        modFamilia.setId_familia(id_familia);
        modFamilia.setServico_programa(String.valueOf(jComboBoxServicoPrograma.getSelectedItem()));
        modFamilia.setUltimo_registro(getDataSistema());
        
        if (jDateChooserIngresso.getDate() == null) {
            modFamilia.setData_ingresso(null);
        } else {
            java.util.Date pegaReceb = jDateChooserIngresso.getDate();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String data = formato.format(pegaReceb);
            modFamilia.setData_ingresso(data);
        }

        if (jDateChooserDesligamento.getDate() == null) {
            modFamilia.setData_desligamento(null);
        } else {
            java.util.Date pegaReceb1 = jDateChooserDesligamento.getDate();
            SimpleDateFormat formato1 = new SimpleDateFormat("yyyy-MM-dd");
            String data1 = formato1.format(pegaReceb1);
            modFamilia.setData_desligamento(data1);
        }
        if (jComboBoxServicoPrograma.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "INFORME O SERVICO/PROGRAMA ANTES DE INSERIR!");
        } else {
            ControleFamilia controlFamilia = new ControleFamilia();
            controlFamilia.InserirFamiliaServico(modFamilia);
            jComboBoxServicoPrograma.setSelectedIndex(0);

            try {
                preencherTabelaServico("select * from fastflowcreas.familia_servico where id_familia =" + id_familia);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }

    }//GEN-LAST:event_jButtonInserirServicoProgramaActionPerformed

    private void preencherTabelaComposicaoFamiliar(String sql) throws SQLException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD", "NOME", "CPF", "RG", "NIS"};
        con.excutaSQL(sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("id_usuario"), con.rs.getString("nome_usuario"), con.rs.getString("cpf"), con.rs.getString("rg"), con.rs.getString("nis")});
            } while (con.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "USUARIO NAO ENCONTRADO");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableComposicaoFamiliar.setModel(modelo);
        jTableComposicaoFamiliar.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableComposicaoFamiliar.getColumnModel().getColumn(0).setResizable(false);
        jTableComposicaoFamiliar.getColumnModel().getColumn(1).setPreferredWidth(350);
        jTableComposicaoFamiliar.getColumnModel().getColumn(1).setResizable(false);
        jTableComposicaoFamiliar.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableComposicaoFamiliar.getColumnModel().getColumn(2).setResizable(false);
        jTableComposicaoFamiliar.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableComposicaoFamiliar.getColumnModel().getColumn(3).setResizable(false);
        jTableComposicaoFamiliar.getColumnModel().getColumn(4).setPreferredWidth(135);
        jTableComposicaoFamiliar.getColumnModel().getColumn(4).setResizable(false);
        jTableComposicaoFamiliar.getTableHeader().setReorderingAllowed(false);
        jTableComposicaoFamiliar.setAutoResizeMode(jTableComposicaoFamiliar.AUTO_RESIZE_OFF);
        jTableComposicaoFamiliar.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void preencherTabelaBeneficio(String sql) throws SQLException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD", "BENEFICIO", "DATA"};
        con.excutaSQL(sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("id_familia_beneficio"), con.rs.getString("beneficio"), con.rs.getString("data_recebimento")});
            } while (con.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SEM REGISTROS");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableBeneficio.setModel(modelo);
        jTableBeneficio.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableBeneficio.getColumnModel().getColumn(0).setResizable(false);
        jTableBeneficio.getColumnModel().getColumn(1).setPreferredWidth(650);
        jTableBeneficio.getColumnModel().getColumn(1).setResizable(false);
        jTableBeneficio.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableBeneficio.getColumnModel().getColumn(2).setResizable(false);
        jTableBeneficio.setAutoResizeMode(jTableBeneficio.AUTO_RESIZE_OFF);
        jTableBeneficio.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void preencherTabelaServico(String sql) throws SQLException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD", "SERVICO/PROGRAMA", "DATA INGRESSO", "DATA DESLIGAMENTO"};
        con.excutaSQL(sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("id_familia_servico"), con.rs.getString("servico_programa"), con.rs.getString("data_ingresso"), con.rs.getString("data_desligamento")});
            } while (con.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SEM REGISTROS");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableServicoPrograma.setModel(modelo);
        jTableServicoPrograma.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableServicoPrograma.getColumnModel().getColumn(0).setResizable(false);
        jTableServicoPrograma.getColumnModel().getColumn(1).setPreferredWidth(650);
        jTableServicoPrograma.getColumnModel().getColumn(1).setResizable(false);
        jTableServicoPrograma.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableServicoPrograma.getColumnModel().getColumn(2).setResizable(false);
        jTableServicoPrograma.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableServicoPrograma.getColumnModel().getColumn(3).setResizable(false);
        jTableServicoPrograma.setAutoResizeMode(jTableServicoPrograma.AUTO_RESIZE_OFF);
        jTableServicoPrograma.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void preencherTabelaUsuarioVinculado(String sql) throws SQLException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD", "NOME", "PARENTESCO", "CPF", "RG", "NIS"};
        con.excutaSQL(sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("id_usuario"), con.rs.getString("nome_usuario"), con.rs.getString("parentesco"), con.rs.getString("cpf"), con.rs.getString("rg"), con.rs.getString("nis")});
            } while (con.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "USUARIO NAO ENCONTRADO");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableUsuarioVinculados.setModel(modelo);
        jTableUsuarioVinculados.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableUsuarioVinculados.getColumnModel().getColumn(0).setResizable(false);
        jTableUsuarioVinculados.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTableUsuarioVinculados.getColumnModel().getColumn(1).setResizable(false);
        jTableUsuarioVinculados.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableUsuarioVinculados.getColumnModel().getColumn(2).setResizable(false);
        jTableUsuarioVinculados.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableUsuarioVinculados.getColumnModel().getColumn(3).setResizable(false);
        jTableUsuarioVinculados.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableUsuarioVinculados.getColumnModel().getColumn(4).setResizable(false);
        jTableUsuarioVinculados.getColumnModel().getColumn(5).setPreferredWidth(135);
        jTableUsuarioVinculados.getColumnModel().getColumn(5).setResizable(false);
        jTableUsuarioVinculados.getTableHeader().setReorderingAllowed(false);
        jTableUsuarioVinculados.setAutoResizeMode(jTableUsuarioVinculados.AUTO_RESIZE_OFF);
        jTableUsuarioVinculados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCadastroFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCadastroFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCadastroFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCadastroFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCadastroFamilia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButtonInserirBeneficio;
    private javax.swing.JButton jButtonInserirServicoPrograma;
    private javax.swing.JButton jButtonInserirUsuario;
    private javax.swing.JButton jButtonNovaFamilia;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxBeneficio;
    private javax.swing.JComboBox<String> jComboBoxEspecificidade;
    private javax.swing.JComboBox<String> jComboBoxParentesco;
    private javax.swing.JComboBox<String> jComboBoxServicoPrograma;
    private com.toedter.calendar.JDateChooser jDateChooserDesligamento;
    private com.toedter.calendar.JDateChooser jDateChooserIngresso;
    private com.toedter.calendar.JDateChooser jDateChooserRecebimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButtonAbastecimentoCarro;
    private javax.swing.JRadioButton jRadioButtonAbastecimentoCisterna;
    private javax.swing.JRadioButton jRadioButtonAbastecimentoOutro;
    private javax.swing.JRadioButton jRadioButtonAbastecimentoPoco;
    private javax.swing.JRadioButton jRadioButtonAbastecimentoRede;
    private javax.swing.JRadioButton jRadioButtonAcesoGeoSim;
    private javax.swing.JRadioButton jRadioButtonAcessoEnerNao;
    private javax.swing.JRadioButton jRadioButtonAcessoEnerSim;
    private javax.swing.JRadioButton jRadioButtonAcessoGeoNao;
    private javax.swing.JRadioButton jRadioButtonAguaNao;
    private javax.swing.JRadioButton jRadioButtonAguaSim;
    private javax.swing.JRadioButton jRadioButtonColetaNao;
    private javax.swing.JRadioButton jRadioButtonColetaSim;
    private javax.swing.JRadioButton jRadioButtonMatAlve;
    private javax.swing.JRadioButton jRadioButtonMatMadeira;
    private javax.swing.JRadioButton jRadioButtonResAlugada;
    private javax.swing.JRadioButton jRadioButtonResCedida;
    private javax.swing.JRadioButton jRadioButtonResOcupada;
    private javax.swing.JRadioButton jRadioButtonResPropria;
    private javax.swing.JRadioButton jRadioButtonViolenciaNao;
    private javax.swing.JRadioButton jRadioButtonViolenciaSim;
    private javax.swing.JRadioButton jRadioButtonZonaNao;
    private javax.swing.JRadioButton jRadioButtonZonaSim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBeneficio;
    private javax.swing.JTable jTableComposicaoFamiliar;
    private javax.swing.JTable jTableServicoPrograma;
    private javax.swing.JTable jTableUsuarioVinculados;
    private javax.swing.JTextField jTextFieldUsuario1;
    // End of variables declaration//GEN-END:variables
}
